### ISSUE TITLE
Time cmd

### ISSUE THREAD

**Issue by Idontneedaname** [LanyK/Teutonica#15]
Finde die struktur ein bisschen unlogisch:
//  aliases: /teutonicatime
//	/tt - TeutonicaTime - Übersicht über die Unterkommandos
//	/tt spielzeit - Eigene Gesamt-Spielzeit (jeder)
//	/tt spielzeit - Fremde Gesamt-Spielzeit (jeder) //sollte vll nur vom Mod eingesehen werden können? -T
//	/tt spielzeit top - Gesamt-Spielzeit-Ranking (jeder) //hier auch nur die Namen, nicht die Zeiten
//	/tt woche - Wochenspielzeit-Ranking und eigene Wochenspielzeit und Reset-Zeitpunkt (jeder)
//	/tt info - Zusammenfassung für den Spieler (Wochenzeit, Gesamtzeit, erstes mal online, letztes mal online) (Moderatoren)
so ist sie gerade.
ich wäre für:
//  aliases: /teutonicatime
//	/tt - TeutonicaTime - Übersicht über die Unterkommandos
//	/tt spielzeit/zeit/time - Current, Weeky, Entire (jeder)
//	/tt spielzeit/zeit/time < player > - Weekly, Entire (mod)
//	/tt rank entire/week - Gesamt/Woche-Spielzeit-Ranking, nur namen, keine zeiten (jeder)
//	/tt rank entire/week - Gesamt/Woche-Spielzeit-Ranking, nur namen, zeiten (mod)
//	/tt info/stats - Zusammenfassung für den Spieler (Current, Week, Entire, erstes mal online, letztes mal online) (jeder)
//	/tt info/stats < player > - Zusammenfassung für den Spieler (Current, Week, Entire, erstes mal online, letztes mal online) (mod)

**Comment by Idontneedaname** [comment]
Mit dem Hintergrundgedanken, dass ein peasant nicht einfach die Gesamtspielzeit von jemand anderem einsehen kann. Deshalb auch keine Zeiten beim ranking (bzw nur bei mods).

**Comment by LanyK** [comment]
Finde die Aufteilung auch besser so.
Bisher war es immer möglich die Zeiten der anderen zu sehen, und es gab nie Probleme oder Beschwerden - ich spreche das heute Abend mal an.

**Comment by LanyK** [comment]
Hast du hier schon was gemacht @Idontneedaname ?
