### ISSUE TITLE
Put Command execution logic of subcommands in /s into private methods

### ISSUE THREAD

**Issue by LanyK** [LanyK/Teutonica#27]
I think this would, by separating the "may he do this" from the "do stuff", make the class more organized.
As dis class is gon be huge.

**Comment by LanyK** [comment]
- Started doing this

**Comment by Idontneedaname** [comment]
Ich werd mir hier überlegen, wie man das am besten verpackt!

**Comment by Idontneedaname** [comment]
Fertig!
